source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/alias
source ~/bin/dotfiles/bash/service
source ~/bin/dotfiles/bash/prompt
source ~/bin/dotfiles/bash/git
source ~/bin/dotfiles/git/alias
source ~/bin/dotfiles/bash/function

### Private configuration
if [ -f ~/.bash_private ]; then
  . ~/.bash_private
fi

export NVM_DIR="/Users/eugenebrodsky/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
